"""initial schema

Revision ID: e6a2a87309e0
Revises: 
Create Date: 2026-07-10 11:18:51.193776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a2a87309e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_valor', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('subcategoria', sa.String(length=120), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('confianca', sa.String(length=10), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('fitid', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regras',
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('subcategoria', sa.String(length=120), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('descricao')
    )
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'nome', name='uq_subcategoria_categoria_nome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategorias')
    op.drop_table('regras')
    op.drop_table('lancamentos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
